# django-mcadmin
# .github/workflows/build.yml


name: "build"
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
  workflow_call:
env:
  NAME: "opensearch"
  DEFAULT_PYTHON_VERSION: "3.10"
jobs:
  check-requirements:
    uses: "./.github/workflows/check-requirements.yml"
  check:
    uses: "./.github/workflows/check.yml"
  test:
    uses: "./.github/workflows/test.yml"
    if: success()
    needs: ["check"]
  coveralls:
    uses: "./.github/workflows/coveralls.yml"
    if: success()
    needs: ["test", "check"]
